# Generated by Django 3.0.5 on 2020-10-22 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimiento', '0004_auto_20201022_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preventivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('preventivo', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.Equipo')),
            ],
        ),
    ]
