# Generated by Django 3.0.5 on 2020-10-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preventivo', '0002_auto_20201022_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preventivo',
            name='dateTime',
        ),
    ]
