# Generated by Django 3.1.5 on 2021-01-31 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='teléfono')),
                ('interno', models.CharField(blank=True, default=None, max_length=50, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='dirección')),
                ('website', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('horario', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='horario de atención')),
                ('comentario', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.rubro')),
            ],
        ),
    ]
