# Generated by Django 3.0.5 on 2020-10-21 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='EstadoTecnico')),
            ],
        ),
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='modelo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Tipo de Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('Servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.Servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='nombre')),
                ('numero_de_serie', models.CharField(max_length=30, unique=True, verbose_name='numero de serie')),
                ('activo', models.BooleanField(default=True)),
                ('dateTimeAlta', models.DateTimeField()),
                ('dateTimeBaja', models.DateTimeField()),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.Marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.Modelo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.Servicio')),
                ('tipoEquipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.TipoEquipo')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='instituto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.Instituto'),
        ),
    ]
