# Generated by Django 3.0.5 on 2020-10-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_auto_20201022_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='dateTimeBaja',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
