# Generated by Django 3.0.5 on 2020-10-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_auto_20201022_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='nombre'),
        ),
    ]
