# Generated by Django 3.1.5 on 2021-01-31 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_auto_20201022_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='dateTimeBaja',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='modelo',
        ),
        migrations.AddField(
            model_name='contacto',
            name='comentario',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipo',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='imagenes'),
        ),
        migrations.AddField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.marca'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='estadotecnico',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
