# Generated by Django 3.1.5 on 2021-01-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotaComunicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('resumen', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='notascomunicacion_file/%Y/%m/%d')),
            ],
        ),
    ]
